src/objects/APITemplate__c.object
<CustomObject>
    <fields>
        <fullName>HitType__c</fullName>
        <label>Hit Type</label>
        <picklist>
            <picklistValues>
                <fullName>pageview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>screenview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>transaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>exception</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>timing</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ObjectAPIName__c</fullName>
        <inlineHelpText>API name of the object. e.g.. Lead or Opportunity</inlineHelpText>
        <label>Object Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Google Analytics Hit Template</label>
    <nameField>
        <label>Hit Template Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Analytics Hit Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APITemplateFieldMapping__c.object
<CustomObject>
    <fields>
        <fullName>APITemplate__c</fullName>
        <label>API Template</label>
        <referenceTo>APITemplate__c</referenceTo>
        <relationshipLabel>API Template Fields</relationshipLabel>
        <relationshipName>APITemplateFieldMapping</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DefaultValue__c</fullName>
        <inlineHelpText>If the value of Salesforce field is null. The default value will be applied.</inlineHelpText>
        <label>Default Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalFieldName__c</fullName>
        <inlineHelpText>External field that will be linked to the Salesforce. eg. ci</inlineHelpText>
        <label>External Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesforceFieldAPIName__c</fullName>
        <inlineHelpText>API Name of the field in Salesforce eg. OtherEmail__c</inlineHelpText>
        <label>Salesforce Field</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>API Template Field Mapping</label>
    <nameField>
        <label>API Template Field Mapping Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Template Fields Mapping</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GoogleAnalyticsApp__c.object
<CustomObject>
    <fields>
        <fullName>TrackingID__c</fullName>
        <label>Tracking ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Google Analytics App</label>
    <nameField>
        <label>External Apps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Analytics App</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GoogleAnalyticsHitQueue__c.object
<CustomObject>
    <fields>
        <fullName>GoogleAnalyticsHitSettingsName__c</fullName>
        <label>Google Analytics Hit Settings Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <label>RecordId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RunInBatch__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Run in Batch</label>
        <type>Checkbox</type>
    </fields>
    <label>Google Analytics Hit Queue</label>
    <nameField>
        <displayFormat>GAQ-{00000}</displayFormat>
        <label>Google Analytics Hit Queue Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Google Analytics Hits Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GoogleAnalyticsHitSettings__c.object
<CustomObject>
    <fields>
        <fullName>GoogleAnalyticsApp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Google Analytics App</label>
        <referenceTo>GoogleAnalyticsApp__c</referenceTo>
        <relationshipLabel>Google Analytics Hit Settings</relationshipLabel>
        <relationshipName>GoogleAnalyticsHitSettings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Google Analytics Hit Settings</label>
    <nameField>
        <label>Hit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Analytics Hit Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GoogleAnalyticsHitStep__c.object
<CustomObject>
    <fields>
        <fullName>APITemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>API Template</label>
        <referenceTo>APITemplate__c</referenceTo>
        <relationshipLabel>Google Analytics Hit Steps</relationshipLabel>
        <relationshipName>GoogleAnalyticsHitSteps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GoogleAnalyticsHitSettings__c</fullName>
        <label>Google Analytics Hit Settings</label>
        <referenceTo>GoogleAnalyticsHitSettings__c</referenceTo>
        <relationshipLabel>Google Analytics Hits Steps</relationshipLabel>
        <relationshipName>GoogleAnalyticsHitsSteps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Google Analytics Hit Step</label>
    <nameField>
        <displayFormat>HS-{0000}</displayFormat>
        <label>Hit Step</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Google Analytics Hits Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GoogleAnalyticsIntegration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>URLEndpoint__c</fullName>
        <label>URLEndpoint</label>
        <type>Url</type>
    </fields>
    <label>Google Analytics Integration</label>
</CustomObject>

src/classes/GoogleAnalyticsServiceTest.cls
@isTest
public class GoogleAnalyticsServiceTest
{
	@testSetup public static void initial(){

		GoogleAnalyticsIntegration__c settings = customSettings();
		insert settings;

		APITemplate__c template = generateTemplate();
		insert template;
		List<APITemplateFieldMapping__c> fieldMapping = generateAPITemplate(template.Id);
		insert fieldMapping;

		GoogleAnalyticsApp__c app = generateApp();
		insert app;

		GoogleAnalyticsHitSettings__c hitSettings = generateHitSettings(app.Id);
		insert hitSettings;
		GoogleAnalyticsHitStep__c hitSettingsSteps = generateHitSteps(template.Id, hitSettings.Id);
		insert hitSettingsSteps;

	}

	@isTest
	static void hitRequest()
	{

		Lead leadR = generateLead();
		insert leadR;

		GoogleAnalyticsHitQueue__c hitQueue = new GoogleAnalyticsHitQueue__c(
			GoogleAnalyticsHitSettingsName__c = 'leadHitSettings',
			RecordId__c = leadR.Id
		);
		Test.setMock(HttpCalloutMock.class, new GAHttpCalloutMock());
		insert hitQueue;

		GoogleAnalyticsService.HitRequest hitRequest = new GoogleAnalyticsService.HitRequest(
			hitQueue.Id, 'leadHitSettings', new Set<Id> { hitQueue.RecordId__c}
		);
	}

	@isTest
	static void sendHitRequest()
	{
		Lead leadR = generateLead();
		insert leadR;

		GoogleAnalyticsHitQueue__c hitQueue = new GoogleAnalyticsHitQueue__c(
			GoogleAnalyticsHitSettingsName__c = 'leadHitSettings',
			RecordId__c = leadR.Id
		);
		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new GAHttpCalloutMock());
		insert hitQueue;
		Test.stopTest();
	}

	@isTest
	static void sendHitRequestBatch()
	{
		Lead leadR = generateLead();
		insert leadR;
		Lead leadR2 = generateLead();
		leadR2.FirstName = 'Google app2';
		insert leadR2;

		GoogleAnalyticsHitQueue__c hitQueue = new GoogleAnalyticsHitQueue__c(
			GoogleAnalyticsHitSettingsName__c = 'leadHitSettings',
			RecordId__c = leadR.Id
		);

		GoogleAnalyticsHitQueue__c hitQueue2 = new GoogleAnalyticsHitQueue__c(
			GoogleAnalyticsHitSettingsName__c = 'leadHitSettings',
			RecordId__c = leadR2.Id
		);
		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new GAHttpCalloutMock());
		insert (new List<GoogleAnalyticsHitQueue__c>{hitQueue, hitqueue2});
		GoogleAnalyticsHitQueue__c[] results = [SELECT Id, RunInBatch__c FROM GoogleAnalyticsHitQueue__c];
		String query = 'SELECT Id, GoogleAnalyticsHitSettingsName__c, RecordId__c FROM GoogleAnalyticsHitQueue__c WHERE RunInBatch__c = TRUE AND Processed__c = FALSE';
		BatchGoogleAnalyticsHitQueue batchjob = new BatchGoogleAnalyticsHitQueue(query);
		batchjob = new BatchGoogleAnalyticsHitQueue();
		Database.executeBatch(batchjob, 2);
		Test.stopTest();

		System.assertEquals(2, results.size());
		for (GoogleAnalyticsHitQueue__c rqueue: results)
			System.assertEquals(TRUE, rqueue.RunInBatch__c);

		results = [SELECT Id, RunInBatch__c FROM GoogleAnalyticsHitQueue__c where Processed__c = true];
		System.assertEquals(2, results.size());
	}

	private static Lead generateLead(){
		Lead record = new Lead (
			FirstName = 'Name 1',
			LastName = 'Last Name',
			Status = 'Open',
			Company = 'Company'
		);
		return record;
	}

	private static GoogleAnalyticsHitSettings__c generateHitSettings(Id appId){
		GoogleAnalyticsHitSettings__c record = new GoogleAnalyticsHitSettings__c (
			Name = 'leadHitSettings',
			GoogleAnalyticsApp__c = appId
		);
		return record;
	}

	private static GoogleAnalyticsIntegration__c customSettings(){
		GoogleAnalyticsIntegration__c record = new GoogleAnalyticsIntegration__c(
			Name = 'GAv1',
			URLEndpoint__c = 'https://www.google-analytics.com/debug/collect?'
		);
		return record;
	}

	private static GoogleAnalyticsApp__c generateApp(){
		GoogleAnalyticsApp__c record = new GoogleAnalyticsApp__c(
			TrackingID__c = 'UA-12345',
			Name = 'App'
		);
		return record;
	}

	private static APITemplate__c generateTemplate(){
		APITemplate__c record = new APITemplate__c(
				Name = 'Template1',
				ObjectAPIName__c = 'Lead',
				HitType__c = 'item'
		);
		return record;
	}

	private static List<APITemplateFieldMapping__c> generateAPITemplate(Id templateId){
		APITemplateFieldMapping__c record1 = new APITemplateFieldMapping__c(
			APITemplate__c = templateId,
			ExternalFieldName__c = 'ci',
			SalesforceFieldAPIName__c = 'Id'
		);
		APITemplateFieldMapping__c record2 = new APITemplateFieldMapping__c(
			APITemplate__c = templateId,
			ExternalFieldName__c = 'ti',
			SalesforceFieldAPIName__c = 'not_defined',
			DefaultValue__c = '99'
		);
		return new List<APITemplateFieldMapping__c> {record1, record2};
	}

	private static GoogleAnalyticsHitStep__c generateHitSteps(Id templateId, Id hitSettings){
		GoogleAnalyticsHitStep__c record = new GoogleAnalyticsHitStep__c(
			APITemplate__c = templateId,
			GoogleAnalyticsHitSettings__c = hitSettings,
			Order__c = 1
		);
		return record;
	}

	public class GAHttpCalloutMock implements HttpCalloutMock{
	  public HttpResponse respond(HTTPRequest req){
	    HttpResponse res = new HttpResponse();
	    res.setStatus('OK');
	    res.setStatusCode(200);
	    res.setBody('Body');
	    return res;
	  }
	}

}