src/objects/GoogleAnalyticsHitQueue__c.object
<CustomObject>
    <fields>
        <fullName>GoogleAnalyticsHitSettingsName__c</fullName>
        <label>Google Analytics Hit Settings Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <label>RecordId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Google Analytics Hit Queue</label>
    <nameField>
        <displayFormat>GAQ-{00000}</displayFormat>
        <label>Google Analytics Hit Queue Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Google Analytics Hits Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GoogleAnalyticsHitQueueTest.cls
@isTest
private class GoogleAnalyticsHitQueueTest
{

    @isTest
    static void triggerTest()
    {
      Lead lead = generateLead();
      insert lead;
      GoogleAnalyticsHitQueue__c hitQueue = generatehitQueue();
      hitQueue.RecordId__c = lead.Id;
      Test.starttest();
      insert hitQueue;
      Test.stopTest();
    }

    private static GoogleAnalyticsHitQueue__c generatehitQueue(){
      GoogleAnalyticsHitQueue__c record = new GoogleAnalyticsHitQueue__c(
        GoogleAnalyticsHitSettingsName__c = 'leadSettings'
      );
      return record;
    }

    private static Lead generateLead(){
      Lead record = new Lead (
        FirstName = 'Name 1',
        LastName = 'Last Name',
        Status = 'Open',
        Company = 'Company'
      );
      return record;
    }
}